export default [
  {
    title: "Full Time Sales Associate - Sydney Boutique",
    contractType: "CDI",
    country: "Australie",
    city: "Sydney",
    className: "job",
    borderColor: "red",
  },
  {
    title: "Agent de Sécurité - Pantin",
    contractType: "CDI",
    country: "France",
    city: "Pantin",
    className: "job",
    borderColor: "#3EA535",
  },
  {
    title: "Responsable d'Atelier (H/F)",
    contractType: "CDD",
    country: "France",
    city: "Paris",
    className: "job",
    borderColor: "#FFEE00",
  },
  {
    title: "Chef de Projets",
    contractType: "CDD",
    country: "France",
    city: "Paris",
    className: "job",
    borderColor: "#039FE3",
  },
  {
    title: "Développeur React.js",
    contractType: "CDI",
    country: "France",
    city: "Paris",
    className: "job",
    borderColor: "#F8C5AF",
  },
  {
    title: "Sales Associate Stockholm",
    contractType: "CDI",
    country: "Suède",
    city: "Stockholm",
    className: "job",
    borderColor: "#E30413",
  },
  {
    title: "Vendeur/se - Crans Montana",
    contractType: "CDI",
    country: "Suisse",
    city: "Crans-Montana",
    className: "job",
    borderColor: "#3EA535",
  },
  {
    title: "CRM & Data Quality Analyst",
    contractType: "CDI",
    country: "USA",
    city: "New York",
    className: "job",
    borderColor: "#FFEE00",
  },
  {
    title: "Infirmier (H/F)",
    contractType: "CDI",
    country: "France",
    city: "Pantin",
    className: "job",
    borderColor: "#039FE3",
  },
];
